# Change these first
owner: geek-cookbook # Your GitHub organization or username, where this repository lives
repo: elfhosted-upptime # The name of this repository

sites:
  - name: Video Hosting Platform
    url: https://video.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200    
  - name: Public Knightcrawler Stremio Addon
    url: https://knighcrawler.elfhosted.com/realdebrid=$RD_KEY/stream/movie/tt0023694.json
    __dangerous__body_down_if_text_missing: White Zombie
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200       
  - name: TorrentIO (not ElfHosted) Addon
    url: https://torrentio.strem.fun/realdebrid=$RD_KEY/stream/movie/tt0023694.json
    __dangerous__body_down_if_text_missing: White Zombie
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200               
  - name: Public Annatar Stremio Addon
    url: https://annatar.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200    
  - name: Public Xtremio Stremio Addon
    url: https://xtremio.elfhosted.com/configure
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200          
  - name: Public MediaFusion Stremio Addon
    url: https://mediafusion.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200   
  - name: Public Stremio-Jackett Addon
    url: https://stremio-jackett.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200   
  - name: Public Shluflix Stremio Addon
    url: https://shluflix.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200     
  - name: Public Stremify Stremio Addon
    url: https://stremify.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200           
  - name: Public Jackettio Stremio Addon
    url: https://jackettio.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200               
  - name: Public Stremio-Jackett Cache
    url: https://stremio-jackett-cacher.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200               
  - name: Stremio CyberFlix Addon
    url: https://cyberflix.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200                                  
  - name: Store / Account Management Platform
    url: https://store.elfhosted.com
    expectedStatusCodes:
      - 200
    assignees:
      - funkypenguin
  - name: Website / Docs
    url: https://elfhosted.com
    expectedStatusCodes:
      - 200
    assignees:
      - funkypenguin      

status-website:
  themeUrl: https://status.elfhosted.com/elfhosted.css    
  cname: status.elfhosted.com
  logoUrl: https://status.elfhosted.com/elfhosted-logo.svg
  faviconSvg: https://status.elfhosted.com/elfhosted-logo.svg
  name: Status | ElfHosted
  introTitle: "**ElfHosted** is an open-source PaaS build by and for geeks"
  introMessage: We engineer our platform to be as automated and resilient as possible, but life happens! If something's not right, check here first, or the [#elf-status](https://discord.com/channels/396055506072109067/1119479124684193933) channel in [Discord](https://chat.funkypenguin.co.nz)!
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://elfhosted.com
    - title: Store
      href: https://store.elfhosted.com
    - title: Discord
      href: https://discord.elfhosted.com
    - title: My Subscriptions
      href: https://store.elfhosted.com/my-account/subscriptions/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
