# Change these first
owner: geek-cookbook # Your GitHub organization or username, where this repository lives
repo: elfhosted-upptime # The name of this repository

sites:
  - name: Video Hosting Platform
    url: https://video.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200    
  - name: Knightcrawler Stremio Addon
    url: https://knightcrawler.elfhosted.com/stream/movie/tt0023694.json
    __dangerous__body_down_if_text_missing: White Zombie
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200       
  - name: TorrentIO (not ElfHosted) Addon
    url: https://torrentio.strem.fun/realdebrid=$RD_KEY/stream/movie/tt0023694.json
    __dangerous__body_down_if_text_missing: White Zombie
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200               
  # not stable
  # - name: Discussio Stremio Addon
  #   url: https://discussio.elfhosted.com
  #   assignees:
  #   - funkypenguin
  #   expectedStatusCodes:
  #     - 200    
  - name: Comet Stremio Addon
    url: https://comet.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200          
  - name: YourIPTV Stremio Addon (not ElfHosted)
    url: https://youriptv.hayd.uk/configure
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200     
  - name: Stremify Stremio Addon (not ElfHosted)
    url: https://stremify.hayd.uk/configure
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200     
  - name: Formulio Stremio Addon (not ElfHosted)
    url: https://formulio.hayd.uk/
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200   
  - name: EasyNews+ Stremio Addon
    url: https://easynewsplus.elfhosted.com/configure
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200                       
  - name: MediaFusion Stremio Addon
    url: https://mediafusion.elfhosted.com/health
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 302   
      - 200
  - name: StremThru Stremio Addons
    url: https://stremthru.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200      
  - name: StremThru Stremio Addons
    url: https://stremthru.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200
  - name: AIOStreams Stremio Addons
    url: https://aiostreams.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200               
  - name: Stremio-Jackett Addon
    url: https://stremio-jackett.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200   
  - name: Zilean
    url: https://zilean.elfhosted.com/healthchecks/ping
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200
  - name: Jackettio Stremio Addon
    url: $JACKETTIO_URL
    __dangerous__body_down_if_text_missing: White Zombie
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200  
  - name: Davio Stremio Addon
    url: https://davio.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200                     
  - name: Stremio-Jackett Cache
    url: https://stremio-jackett-cacher.elfhosted.com
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200               
  - name: Stremio CyberFlix Addon
    url: https://cyberflix.elfhosted.com/health
    __dangerous__body_down_if_text_missing: ok
    maxResponseTime: 5000
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200            
  - name: Stremio TMDB Addon
    url: https://tmdb.elfhosted.com/configure
    maxResponseTime: 5000
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200   
  - name: Speed Test Endpoint US-WA
    url: https://eagle02-speed.elfhosted.cc/empty.php
    maxResponseTime: 5000
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200   
  - name: Speed Test Endpoint DE-FSN
    url: https://fairy01-speed.elfhosted.com/empty.php
    maxResponseTime: 5000
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200      
  - name: FNKY Link Shortener
    url: https://fnky.nz
    maxResponseTime: 5000
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 302
  - name: Debrid.News
    url: https://debrid.news
    maxResponseTime: 5000
    assignees:
    - funkypenguin
    expectedStatusCodes:
      - 200                            
  - name: Store / Account Management Platform
    url: https://store.elfhosted.com
    expectedStatusCodes:
      - 200
    assignees:
      - funkypenguin
  - name: Website / Docs
    url: https://docs.elfhosted.com
    expectedStatusCodes:
      - 200
    assignees:
      - funkypenguin      

status-website:
  themeUrl: https://status.elfhosted.com/elfhosted.css    
  cname: status.elfhosted.com
  logoUrl: https://status.elfhosted.com/elfhosted-logo.svg
  faviconSvg: https://status.elfhosted.com/elfhosted-logo.svg
  name: Status | ElfHosted
  introTitle: "**ElfHosted** is an open-source PaaS build by and for geeks"
  introMessage: We engineer our platform to be as automated and resilient as possible, but life happens! If something's not right, check here first, or the [#elf-status](https://discord.com/channels/396055506072109067/1119479124684193933) channel in [Discord](https://chat.funkypenguin.co.nz)!
  navbar:
    - title: Status
      href: /
    - title: Docs
      href: https://docs.elfhosted.com
    - title: Store
      href: https://store.elfhosted.com
    - title: Discord
      href: https://discord.elfhosted.com
    - title: My Subscriptions
      href: https://store.elfhosted.com/my-account/subscriptions/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
